// SPDX-License-Identifier: Apache-2.0
//! Per-kernel fixture validation. A statement-for-statement port of
//! `tests/unit/test_ops.c`.
//!
//! Each fixture under `fixtures/ops/` is generated by `tools/emit_fixtures.py` from the
//! pure-torch reference and carries its own weights, inputs and expected outputs. These
//! tests read them and assert the Rust kernels reproduce the reference, within the
//! manifest's tolerances.
//!
//! Tolerances come from `fixtures/ops/MANIFEST.json` (its `tolerance.fp32_abs` /
//! `fp32_rel` keys), falling back to `1e-4` / `1e-3` only when the manifest is absent. A
//! skipped case is a failure, exactly as the C harness counts a skip as a non-zero exit;
//! no test here skips.

// The kernels under test are a statement-for-statement port of the C source, and this
// harness mirrors `tests/unit/test_ops.c` the same way: the index loops and the wide
// fixture-driven signatures are what keep the two diffable side by side.
#![allow(clippy::needless_range_loop, clippy::too_many_arguments)]

mod support;
use support::{
    arr, arr_u8, assert_abs_max, assert_close, boolean, num_f32, num_i32, shape, Fixtures,
};

use k3::cfg::Cfg;
use k3::ops::{
    attn_res, decoder_layer, kda_decay, kda_layer, kda_step, matmul, matmul_bf16, matmul_mxfp4,
    mla, moe, mxfp4_dequant, rmsnorm, router, shortconv, situ_glu, Attn, KdaW, LayerW, MlaW, MoeW,
    WMat,
};
use k3::ops::{bf16f, l2norm};

// ---------------------------------------------------------------------- helpers ----

/// Pack the routed expert weights from a fixture into one contiguous bank, exactly as
/// C's `pack_experts` does. The MoE kernels index the bank as `w1[expert * inter * latent
/// ..]`, `w3` the same, and `w2[expert * latent * inter ..]`. test_ops.c:612.
fn pack_experts(r: &serde_json::Value, fmt: &str, n: usize, per: usize) -> Vec<f32> {
    let mut w = vec![0.0f32; per * n];
    for e in 0..n {
        let key = fmt.replace("{}", &e.to_string());
        let a = arr(r, &key);
        assert_eq!(a.len(), per, "expert {e} key {key}: {} != {}", a.len(), per);
        w[e * per..(e + 1) * per].copy_from_slice(&a);
    }
    w
}
/// A `Cfg` with every field zeroed, the Rust equivalent of C's `memset(&c, 0, sizeof c)`.
/// `Cfg` does not derive `Default` (it owns a `Vec`), so the tests build it literally.
/// This mirrors `cfg::Cfg::from_value` and `main::real_cfg_hardcoded`, which both construct
/// the struct field by field. scale_test.c:57.
fn cfg_zero() -> Cfg {
    Cfg {
        hidden: 0,
        n_layers: 0,
        vocab: 0,
        rms_eps: 0.0,
        kda_heads: 0,
        kda_head_dim: 0,
        conv_k: 0,
        gate_lb: 0.0,
        n_heads: 0,
        q_lora: 0,
        kv_lora: 0,
        qk_nope: 0,
        qk_rope: 0,
        v_head: 0,
        mla_out_gate: 0,
        n_experts: 0,
        topk: 0,
        n_shared: 0,
        latent: 0,
        moe_inter: 0,
        routed_scale: 0.0,
        moe_renorm: 0,
        latent_norm: 0,
        first_dense: 0,
        dense_inter: 0,
        attn_res_block: 0,
        situ_b1: 0.0,
        situ_b2: 0.0,
        full_attn: Vec::new(),
    }
}

// ---------------------------------------------------------------------- rmsnorm ----

#[test]
fn rmsnorm_case() {
    // t_rmsnorm. test_ops.c:130.
    let f = Fixtures::ops();
    let r = f.load("rmsnorm");
    let w = arr(&r, "weight");
    let x = arr(&r, "in");
    let e = arr(&r, "out");
    let eps = num_f32(&r, "eps", 1e-5);
    let n = w.len();
    let rows = x.len() / n;
    let mut y = vec![0.0f32; x.len()];
    for i in 0..rows {
        rmsnorm(&mut y[i * n..(i + 1) * n], &x[i * n..(i + 1) * n], &w, eps);
    }
    assert_close("rmsnorm", &y, &e, f.atol, f.rtol);
}

// ---------------------------------------------------------------------- situ_glu ----

#[test]
fn situ_glu_case() {
    // t_situ. test_ops.c:148. SiTU-GLU over a `[R, 2*W]` input laid out `[gate | up]`.
    let f = Fixtures::ops();
    let r = f.load("situ_glu");
    let x = arr(&r, "in");
    let e = arr(&r, "out");
    let b1 = num_f32(&r, "beta", 4.0);
    let b2 = num_f32(&r, "linear_beta", 25.0);
    let din = shape(&r, "in");
    let dout = shape(&r, "out");
    assert_eq!(din.len(), 2, "situ_glu: in must be rank 2");
    assert_eq!(dout.len(), 2, "situ_glu: out must be rank 2");
    let rows = dout[0] as usize;
    let w = dout[1] as usize;
    assert_eq!(
        din[0] as usize, rows,
        "situ_glu: in row count {} != out row count {}",
        din[0], rows
    );
    assert_eq!(
        din[1] as usize,
        2 * w,
        "situ_glu: in width {} != 2 * out width {}",
        din[1],
        2 * w
    );
    let mut y = vec![0.0f32; e.len()];
    for i in 0..rows {
        situ_glu(
            &mut y[i * w..(i + 1) * w],
            &x[i * 2 * w..(i + 1) * 2 * w],
            b1,
            b2,
        );
    }
    assert_close("situ_glu", &y, &e, f.atol, f.rtol);

    // The soft cap is the one property SiTU-GLU guarantees: |out| <= b1*b2, for any input
    // whatsoever. Violating it means a tanh was dropped or applied to the wrong operand,
    // so this counts as a failure rather than a warning. test_ops.c:176.
    let mx = y.iter().fold(0.0f32, |a, &v| a.max(v.abs()));
    assert!(
        mx <= b1 * b2 + 1e-2,
        "situ_glu: |out|={mx:.3} exceeds b1*b2={} (a tanh is missing or applied to the wrong operand)",
        b1 * b2
    );
}

// ---------------------------------------------------------------------- shortconv ----

#[test]
fn shortconv_case() {
    // t_shortconv. test_ops.c:190. The fixture's weight is `[channels, 1, k]` which
    // flattens to `[channels][k]`, the layout `shortconv_ip` indexes as `w[c*k + j]`.
    let f = Fixtures::ops();
    let r = f.load("shortconv");
    let w = arr(&r, "weight");
    let x = arr(&r, "in");
    let e = arr(&r, "out");
    let st = arr(&r, "state_after");
    let xn = arr(&r, "in_next");
    let en = arr(&r, "out_next");
    let k = num_i32(&r, "kernel", 4) as usize;
    let c = num_i32(&r, "channels", 0) as usize;
    assert!(c > 0, "shortconv: channels missing");
    let t_len = x.len() / c;
    let mut y = vec![0.0f32; x.len()];
    let mut s = vec![0.0f32; c * (k - 1)];
    shortconv(&mut y, &x, &w, Some(&mut s), c, k, t_len);
    assert_close("shortconv", &y, &e, f.atol, f.rtol);
    assert_close("conv_state", &s, &st, f.atol, f.rtol);

    // CONTINUATION. Feed the state from the first call straight into a second call over
    // in_next, and require out_next. This is the only check in the suite that can see the
    // READ side of the state. test_ops.c:216.
    let t2 = xn.len() / c;
    let mut y2 = vec![0.0f32; xn.len()];
    shortconv(&mut y2, &xn, &w, Some(&mut s), c, k, t2);
    assert_close("conv_continuation", &y2, &en, f.atol, f.rtol);
}

// ---------------------------------------------------------------------- kda_decay ----

#[test]
fn kda_decay_case() {
    // t_decay. test_ops.c:231. Drives the engine's own decay kernel forward from the
    // fixture's z and compares its g/alpha to torch elementwise. The absolute 1e-5 bound
    // is the C test's own, not the manifest tolerance.
    let f = Fixtures::ops();
    let r = f.load("kda_decay");
    let a_log = arr(&r, "A_log");
    let dt_bias = arr(&r, "dt_bias");
    let eg = arr(&r, "g");
    let ea = arr(&r, "alpha");
    let z = arr(&r, "z");
    let lb = num_f32(&r, "lower_bound", -5.0);
    let h = a_log.len();
    let d = dt_bias.len() / h;
    let tok = z.len() / dt_bias.len();
    let mut gc = vec![0.0f32; eg.len()];
    let mut ac = vec![0.0f32; ea.len()];
    let nb = dt_bias.len();
    for t in 0..tok {
        kda_decay(
            &mut gc[t * nb..(t + 1) * nb],
            &mut ac[t * nb..(t + 1) * nb],
            &z[t * nb..(t + 1) * nb],
            &a_log,
            &dt_bias,
            h,
            d,
            lb,
        );
    }
    // A_log spans linspace(-0.4, 1.2) across heads, so a per-channel misindex moves every
    // element and shows up here immediately. test_ops.c:262.
    assert_abs_max("kda_decay_g", &gc, &eg, 1e-5);
    assert_abs_max("kda_decay_alpha", &ac, &ea, 1e-5);
}

// ---------------------------------------------------------------------- kda_recur ----

fn kda_recur_case(file: &str) {
    // t_recur. test_ops.c:307. The isolated recurrence: decay, then the rank-one delta
    // write, then read the ALREADY UPDATED state. Any permutation runs cleanly and
    // produces a wrong model, so it gets its own test at T=1 and T=8.
    let f = Fixtures::ops();
    let r = f.load(file);
    let t = num_i32(&r, "T", 0) as usize;
    let h = num_i32(&r, "H", 0) as usize;
    let dk = num_i32(&r, "d_k", 0) as usize;
    let dv = num_i32(&r, "d_v", dk as i32) as usize;
    let qs = num_f32(&r, "q_scale", 1.0);
    let q = arr(&r, "q");
    let k = arr(&r, "k");
    let v = arr(&r, "v");
    let al = arr(&r, "alpha");
    let bt = arr(&r, "beta");
    let eo = arr(&r, "out");
    let es = arr(&r, "state_out");
    assert!(t > 0 && h > 0 && dk > 0, "{file}: T/H/d_k missing");

    let mut s = vec![0.0f32; h * dk * dv];
    let mut out = vec![0.0f32; t * h * dv];
    let mut qs_ = vec![0.0f32; dk];
    for ti in 0..t {
        for head in 0..h {
            let off = (ti * h + head) * dk;
            for i in 0..dk {
                qs_[i] = q[off + i] * qs; // d_k^-0.5
            }
            kda_step(
                &mut s[head * dk * dv..(head + 1) * dk * dv],
                &mut out[(ti * h + head) * dv..(ti * h + head + 1) * dv],
                &qs_,
                &k[off..off + dk],
                &v[off..off + dk],
                &al[(ti * h + head) * dk..(ti * h + head + 1) * dk],
                bt[ti * h + head],
                dk,
                dv,
            );
        }
    }
    assert_close(&format!("{file}_out"), &out, &eo, f.atol, f.rtol);
    assert_close(&format!("{file}_state"), &s, &es, f.atol, f.rtol);
}

#[test]
fn kda_recur1() {
    kda_recur_case("kda_recur1");
}

#[test]
fn kda_recur8() {
    kda_recur_case("kda_recur8");
}

// ---------------------------------------------------------------------- router ----

#[test]
fn router_case() {
    // t_router. test_ops.c:350. Indices are compared as SETS because the reference uses
    // topk(sorted=False), whose order is unspecified. Weights are matched by expert id.
    let f = Fixtures::ops();
    let r = f.load("router");
    let w = arr(&r, "gate_weight");
    let bias = arr(&r, "bias");
    let x = arr(&r, "in");
    let eidx = arr(&r, "topk_idx");
    let ewt = arr(&r, "topk_weight");
    let k = num_i32(&r, "top_k", 0) as usize;
    let e = num_i32(&r, "n_experts", 0) as usize;
    assert!(k > 0 && e > 0, "router: top_k/n_experts missing");
    let hidden = w.len() / e;
    let rows = x.len() / hidden;
    let mut gi = vec![0i32; k];
    let mut gw = vec![0.0f32; k];
    let mut set_ok = true;
    let mut worst_w = 0.0f64;
    for rw in 0..rows {
        router(
            &mut gi,
            &mut gw,
            &x[rw * hidden..(rw + 1) * hidden],
            &w,
            Some(&bias),
            hidden,
            e,
            k,
            true,
            1.0,
        );
        // compare index SETS
        for a in 0..k {
            let mut found = false;
            for b in 0..k {
                if eidx[rw * k + b] as i32 == gi[a] {
                    found = true;
                    break;
                }
            }
            if !found {
                set_ok = false;
                eprintln!(
                    "        row {rw}: C picked expert {}, reference did not",
                    gi[a]
                );
            }
        }
        // match weights by expert id, since order is unspecified
        for a in 0..k {
            for b in 0..k {
                if eidx[rw * k + b] as i32 != gi[a] {
                    continue;
                }
                let d = (gw[a] as f64 - ewt[rw * k + b] as f64).abs();
                let tol = f.atol + f.rtol * (ewt[rw * k + b] as f64).abs();
                if d / tol > worst_w {
                    worst_w = d / tol;
                }
            }
        }
    }
    assert!(set_ok, "router: index sets do not match reference");
    assert!(
        worst_w <= 1.0,
        "router: worst weight {:.2}x tol exceeds 1.0x",
        worst_w
    );
}

// ---------------------------------------------------------------------- attnres ----

#[test]
fn attnres_case() {
    // t_attnres. test_ops.c:277. The fixture carries a fold_hint (norm.weight *
    // proj.weight already folded) and the raw block_residual + prefix_sum sources.
    let f = Fixtures::ops();
    let r = f.load("attnres");
    let px = arr(&r, "prefix_sum");
    let br = arr(&r, "block_residual");
    let fold = arr(&r, "fold_hint");
    let e = arr(&r, "out");
    let eps = num_f32(&r, "eps", 1e-5);
    let n = fold.len();
    let rows = px.len() / n;
    let nblk = br.len() / (rows * n);
    let nsrc = nblk + 1;
    let mut src = vec![0.0f32; nsrc * n];
    let mut y = vec![0.0f32; rows * n];
    for rw in 0..rows {
        for b in 0..nblk {
            src[b * n..(b + 1) * n]
                .copy_from_slice(&br[(rw * nblk + b) * n..(rw * nblk + b + 1) * n]);
        }
        src[nblk * n..(nblk + 1) * n].copy_from_slice(&px[rw * n..(rw + 1) * n]);
        attn_res(&mut y[rw * n..(rw + 1) * n], &src, &fold, nsrc, n, eps);
    }
    assert_close("attn_res", &y, &e, f.atol, f.rtol);
}

// ---------------------------------------------------------------------- mla ----

#[test]
fn mla_case() {
    // t_mla. test_ops.c:407. Gated MLA with all eight weight tensors. The softmax scale is
    // over the full head width (qk_nope + qk_rope), the single-head k_rope is broadcast,
    // and the gate is applied BEFORE o_proj with no norm.
    let f = Fixtures::ops();
    let r = f.load("mla");
    let mut c = cfg_zero();
    c.qk_nope = num_i32(&r, "qk_nope", 0);
    c.qk_rope = num_i32(&r, "qk_rope", 0);
    c.kv_lora = num_i32(&r, "kv_lora", 0);
    c.q_lora = num_i32(&r, "q_lora", 0);
    c.v_head = num_i32(&r, "v_head", 0);
    c.n_heads = num_i32(&r, "n_heads", 0);
    c.rms_eps = num_f32(&r, "rms_eps", 1e-5);

    let x = arr(&r, "in");
    let eo = arr(&r, "out");
    let q_a = arr(&r, "q_a_proj_weight");
    let q_a_norm = arr(&r, "q_a_layernorm_weight");
    let q_b = arr(&r, "q_b_proj_weight");
    let kv_a = arr(&r, "kv_a_proj_with_mqa_weight");
    let kv_a_norm = arr(&r, "kv_a_layernorm_weight");
    let kv_b = arr(&r, "kv_b_proj_weight");
    let o = arr(&r, "o_proj_weight");
    let g = arr(&r, "g_proj_weight");

    let din = shape(&r, "in");
    let t = din[1] as usize;
    c.hidden = din[2] as i32;

    let w = MlaW {
        q_a: WMat::F32(&q_a),
        q_b: WMat::F32(&q_b),
        kv_a: WMat::F32(&kv_a),
        kv_b: WMat::F32(&kv_b),
        o: WMat::F32(&o),
        g: Some(WMat::F32(&g)),
        q_a_norm: &q_a_norm,
        kv_a_norm: &kv_a_norm,
    };
    let scratch_len = k3::ops::mla_scratch(&c, t);
    let mut scratch = vec![0.0f32; scratch_len];
    let mut y = vec![0.0f32; t * c.hidden as usize];
    mla(&mut y, &x, &w, &c, t, &mut scratch);
    assert_close("mla", &y, &eo, f.atol, f.rtol);
}

// ---------------------------------------------------------------------- moe ----

#[test]
fn moe_case() {
    // t_moe. test_ops.c:465. Stable LatentMoE: route full-width, down-project, experts in
    // latent, aggregate RMSNorm, up-project, then the unweighted shared expert.
    let f = Fixtures::ops();
    let r = f.load("moe");
    let mut c = cfg_zero();
    c.hidden = num_i32(&r, "hidden", 0);
    c.latent = num_i32(&r, "latent", 0);
    c.moe_inter = num_i32(&r, "moe_inter", 0);
    c.n_experts = num_i32(&r, "n_experts", 0);
    c.topk = num_i32(&r, "top_k", 0);
    c.n_shared = num_i32(&r, "n_shared", 0);
    c.routed_scale = num_f32(&r, "routed_scale", 1.0);
    c.moe_renorm = num_i32(&r, "renorm", 1);
    c.latent_norm = num_i32(&r, "latent_norm", 1);
    c.rms_eps = num_f32(&r, "rms_eps", 1e-5);
    c.situ_b1 = num_f32(&r, "situ_b1", 4.0);
    c.situ_b2 = num_f32(&r, "situ_b2", 25.0);

    let x = arr(&r, "in");
    let eo = arr(&r, "out");
    let gate = arr(&r, "gate_weight");
    let bias = arr(&r, "e_score_correction_bias");
    let down = arr(&r, "down_weight");
    let up = arr(&r, "up_weight");
    let norm = arr(&r, "norm_weight");
    let sh1 = arr(&r, "shared_w1_weight");
    let sh3 = arr(&r, "shared_w3_weight");
    let sh2 = arr(&r, "shared_w2_weight");

    // routed experts arrive as experts_N_wK_weight; pack them contiguously.
    let per13 = (c.moe_inter * c.latent) as usize;
    let per2 = (c.latent * c.moe_inter) as usize;
    let w1 = pack_experts(&r, "experts_{}_w1_weight", c.n_experts as usize, per13);
    let w3 = pack_experts(&r, "experts_{}_w3_weight", c.n_experts as usize, per13);
    let w2 = pack_experts(&r, "experts_{}_w2_weight", c.n_experts as usize, per2);

    let din = shape(&r, "in");
    let t = din[1] as usize;
    let topk = c.topk as usize;
    let mut idx = vec![0i32; topk];
    let mut wt = vec![0.0f32; topk];
    let mut sc = vec![0.0f32; k3::ops::moe_scratch(&c)];
    let mut y = vec![0.0f32; t * c.hidden as usize];

    let w = MoeW {
        gate: &gate,
        bias: Some(&bias),
        w1: Some(&w1),
        w3: Some(&w3),
        w2: Some(&w2),
        latent_norm: Some(&norm),
        down: WMat::F32(&down),
        up: WMat::F32(&up),
        sh1: WMat::F32(&sh1),
        sh3: WMat::F32(&sh3),
        sh2: WMat::F32(&sh2),
        layer: 0,
        cache_only: false,
    };
    // Resident fixtures: no expert source. `moe` uses the packed w1/w3/w2 bank.
    moe(&mut y, &x, &w, &c, t, &mut idx, &mut wt, &mut sc, None);
    assert_close("moe", &y, &eo, f.atol, f.rtol);
}

// ---------------------------------------------------------------------- kda_layer ----

fn kda_layer_case(file: &str) {
    // t_kda_layer. test_ops.c:552. The full KDA layer: projections, three depthwise convs
    // with fused SiLU, L2Norm on q/k only, the shared low-rank decay, the per-head beta,
    // the recurrence, the head-wise norm and the gate in THAT order, then the output
    // projection. Run at T=1 (decode) and T=8 (where an ordering bug compounds).
    let f = Fixtures::ops();
    let r = f.load(file);
    let mut c = cfg_zero();
    c.kda_heads = num_i32(&r, "H", 0);
    c.kda_head_dim = num_i32(&r, "d_k", 0);
    c.conv_k = num_i32(&r, "conv_k", 4);
    c.gate_lb = num_f32(&r, "lower_bound", -5.0);
    c.rms_eps = num_f32(&r, "rms_eps", 1e-5);

    let x = arr(&r, "in");
    let eo = arr(&r, "out");
    let es = arr(&r, "state_out");

    let q = arr(&r, "q_proj");
    let k = arr(&r, "k_proj");
    let v = arr(&r, "v_proj");
    let q_conv = arr(&r, "q_conv");
    let k_conv = arr(&r, "k_conv");
    let v_conv = arr(&r, "v_conv");
    let f_a = arr(&r, "f_a");
    let f_b = arr(&r, "f_b");
    let a_log = arr(&r, "A_log");
    let dt_bias = arr(&r, "dt_bias");
    let b = arr(&r, "b_proj");
    let g = arr(&r, "g_proj");
    let o_norm = arr(&r, "o_norm");
    let o = arr(&r, "o_proj");

    let din = shape(&r, "in");
    let t = din[1] as usize;
    c.hidden = din[2] as i32;

    let w = KdaW {
        q: WMat::F32(&q),
        k: WMat::F32(&k),
        v: WMat::F32(&v),
        q_conv: &q_conv,
        k_conv: &k_conv,
        v_conv: &v_conv,
        f_a: WMat::F32(&f_a),
        f_b: WMat::F32(&f_b),
        a_log: &a_log,
        dt_bias: &dt_bias,
        b: WMat::F32(&b),
        g: WMat::F32(&g),
        o_norm: &o_norm,
        o: WMat::F32(&o),
    };
    let p = (c.kda_heads * c.kda_head_dim) as usize;
    let hist = (c.conv_k - 1) as usize;
    let mut st = vec![0.0f32; p * c.kda_head_dim as usize + 3 * p * hist];
    let mut sc = vec![0.0f32; k3::ops::kda_scratch(&c, t)];
    let mut y = vec![0.0f32; t * c.hidden as usize];
    kda_layer(&mut y, &x, &w, &c, t, Some(&mut st), &mut sc);
    assert_close(&format!("{file}_out"), &y, &eo, f.atol, f.rtol);
    // The fixture records only the recurrent matrix (H*D*D); the buffer also carries the
    // ShortConv history behind it. C's report() compares the fixture's length, so slice.
    assert_close(
        &format!("{file}_state"),
        &st[..es.len()],
        &es,
        f.atol,
        f.rtol,
    );
}

#[test]
fn kda_layer1() {
    kda_layer_case("kda_layer1");
}

#[test]
fn kda_layer8() {
    kda_layer_case("kda_layer8");
}

// ---------------------------------------------------------------------- layer ----

/// Owned storage for the MoE weight matrices and the packed routed-expert bank, kept
/// alive in the test's scope so the `MoeW` that borrows it is valid through the
/// `decoder_layer` call. This is what C holds on the stack: the packed `float *` plus the
/// flat weight arrays, all owned by `t_layer`'s frame. test_ops.c:693-704.
struct LayerMoeWeights {
    gate: Vec<f32>,
    bias: Vec<f32>,
    down: Vec<f32>,
    up: Vec<f32>,
    norm: Vec<f32>,
    sh1: Vec<f32>,
    sh3: Vec<f32>,
    sh2: Vec<f32>,
    w1: Vec<f32>,
    w3: Vec<f32>,
    w2: Vec<f32>,
}

impl LayerMoeWeights {
    /// Load and pack all the MoE weights for a layer fixture. The routed expert bank is
    /// packed contiguously exactly as C's inline loop does: `w1[expert * inter * latent]`,
    /// `w3` the same, `w2[expert * latent * inter]`.
    fn load(r: &serde_json::Value, c: &Cfg) -> LayerMoeWeights {
        let per13 = (c.moe_inter * c.latent) as usize;
        let per2 = (c.latent * c.moe_inter) as usize;
        LayerMoeWeights {
            gate: arr(r, "mlp_gate_weight"),
            bias: arr(r, "mlp_e_score_correction_bias"),
            down: arr(r, "mlp_down_weight"),
            up: arr(r, "mlp_up_weight"),
            norm: arr(r, "mlp_norm_weight"),
            sh1: arr(r, "mlp_shared_w1_weight"),
            sh3: arr(r, "mlp_shared_w3_weight"),
            sh2: arr(r, "mlp_shared_w2_weight"),
            w1: pack_experts(r, "mlp_experts_{}_w1_weight", c.n_experts as usize, per13),
            w3: pack_experts(r, "mlp_experts_{}_w3_weight", c.n_experts as usize, per13),
            w2: pack_experts(r, "mlp_experts_{}_w2_weight", c.n_experts as usize, per2),
        }
    }

    /// Build the borrow-checked view. Resident fixtures: no expert source.
    fn view(&self) -> MoeW<'_> {
        MoeW {
            gate: &self.gate,
            bias: Some(&self.bias),
            w1: Some(&self.w1),
            w3: Some(&self.w3),
            w2: Some(&self.w2),
            latent_norm: Some(&self.norm),
            down: WMat::F32(&self.down),
            up: WMat::F32(&self.up),
            sh1: WMat::F32(&self.sh1),
            sh3: WMat::F32(&self.sh3),
            sh2: WMat::F32(&self.sh2),
            layer: 0,
            cache_only: false,
        }
    }
}

/// Owned storage for one attention flavour's weights. Exactly one of the MLA block or
/// the KDA block is populated, matching the `is_mla` field in the fixture. The shared
/// norm/proj weights (`in_norm`, `post_norm`, `attn_res_*`, `mlp_res_*`) live in
/// `layer_case` directly, since they are present for both flavours. test_ops.c:665-691.
struct LayerAttnWeights {
    // MLA
    q_a: Vec<f32>,
    q_a_norm: Vec<f32>,
    q_b: Vec<f32>,
    kv_a: Vec<f32>,
    kv_a_norm: Vec<f32>,
    kv_b: Vec<f32>,
    o: Vec<f32>,
    g: Vec<f32>,
    // KDA
    q: Vec<f32>,
    k: Vec<f32>,
    v: Vec<f32>,
    q_conv: Vec<f32>,
    k_conv: Vec<f32>,
    v_conv: Vec<f32>,
    f_a: Vec<f32>,
    f_b: Vec<f32>,
    a_log: Vec<f32>,
    dt_bias: Vec<f32>,
    b: Vec<f32>,
    o_norm: Vec<f32>,
}

impl LayerAttnWeights {
    fn load(r: &serde_json::Value, is_mla: bool) -> LayerAttnWeights {
        if is_mla {
            LayerAttnWeights {
                q_a: arr(r, "self_attn_q_a_proj_weight"),
                q_a_norm: arr(r, "self_attn_q_a_layernorm_weight"),
                q_b: arr(r, "self_attn_q_b_proj_weight"),
                kv_a: arr(r, "self_attn_kv_a_proj_with_mqa_weight"),
                kv_a_norm: arr(r, "self_attn_kv_a_layernorm_weight"),
                kv_b: arr(r, "self_attn_kv_b_proj_weight"),
                o: arr(r, "self_attn_o_proj_weight"),
                g: arr(r, "self_attn_g_proj_weight"),
                q: Vec::new(),
                k: Vec::new(),
                v: Vec::new(),
                q_conv: Vec::new(),
                k_conv: Vec::new(),
                v_conv: Vec::new(),
                f_a: Vec::new(),
                f_b: Vec::new(),
                a_log: Vec::new(),
                dt_bias: Vec::new(),
                b: Vec::new(),
                o_norm: Vec::new(),
            }
        } else {
            LayerAttnWeights {
                q_a: Vec::new(),
                q_a_norm: Vec::new(),
                q_b: Vec::new(),
                kv_a: Vec::new(),
                kv_a_norm: Vec::new(),
                kv_b: Vec::new(),
                // KDA's full-rank gate, shared field name with MLA's output gate.
                g: arr(r, "self_attn_g_proj_weight"),
                q: arr(r, "self_attn_q_proj_weight"),
                k: arr(r, "self_attn_k_proj_weight"),
                v: arr(r, "self_attn_v_proj_weight"),
                q_conv: arr(r, "self_attn_q_conv1d_weight"),
                k_conv: arr(r, "self_attn_k_conv1d_weight"),
                v_conv: arr(r, "self_attn_v_conv1d_weight"),
                f_a: arr(r, "self_attn_f_a_proj_weight"),
                f_b: arr(r, "self_attn_f_b_proj_weight"),
                a_log: arr(r, "self_attn_A_log"),
                dt_bias: arr(r, "self_attn_dt_bias"),
                b: arr(r, "self_attn_b_proj_weight"),
                o_norm: arr(r, "self_attn_o_norm_weight"),
                o: arr(r, "self_attn_o_proj_weight"),
            }
        }
    }

    fn view(&self, is_mla: bool) -> Attn<'_> {
        if is_mla {
            Attn::Mla(MlaW {
                q_a: WMat::F32(&self.q_a),
                q_b: WMat::F32(&self.q_b),
                kv_a: WMat::F32(&self.kv_a),
                kv_b: WMat::F32(&self.kv_b),
                o: WMat::F32(&self.o),
                g: Some(WMat::F32(&self.g)),
                q_a_norm: &self.q_a_norm,
                kv_a_norm: &self.kv_a_norm,
            })
        } else {
            Attn::Kda(KdaW {
                q: WMat::F32(&self.q),
                k: WMat::F32(&self.k),
                v: WMat::F32(&self.v),
                q_conv: &self.q_conv,
                k_conv: &self.k_conv,
                v_conv: &self.v_conv,
                f_a: WMat::F32(&self.f_a),
                f_b: WMat::F32(&self.f_b),
                a_log: &self.a_log,
                dt_bias: &self.dt_bias,
                b: WMat::F32(&self.b),
                g: WMat::F32(&self.g),
                o_norm: &self.o_norm,
                o: WMat::F32(&self.o),
            })
        }
    }
}

fn layer_case(file: &str) {
    // t_layer. test_ops.c:627. A whole decoder layer: AttnRes wiring plus attention plus
    // MoE. The C test hardcodes the model-level config (n_layers=13, etc.) and reads only
    // the per-layer dims from the fixture.
    let f = Fixtures::ops();
    let r = f.load(file);
    let li = num_i32(&r, "layer_idx", 0);
    let is_mla = boolean(&r, "is_mla", 0) != 0;

    let mut c = cfg_zero();
    c.hidden = num_i32(&r, "hidden", 0);
    c.rms_eps = num_f32(&r, "rms_eps", 1e-5);
    c.attn_res_block = num_i32(&r, "attn_res_block_size", 3);
    c.n_layers = 13;
    c.kda_heads = 4;
    c.kda_head_dim = 16;
    c.conv_k = 4;
    c.gate_lb = -5.0;
    c.n_heads = 4;
    c.q_lora = 64;
    c.kv_lora = 32;
    c.qk_nope = 24;
    c.qk_rope = 8;
    c.v_head = 16;
    c.mla_out_gate = 1;
    c.n_experts = 8;
    c.topk = 2;
    c.n_shared = 2;
    c.latent = 64;
    c.moe_inter = 48;
    c.routed_scale = 1.0;
    c.moe_renorm = 1;
    c.latent_norm = 1;
    c.situ_b1 = 4.0;
    c.situ_b2 = 25.0;
    c.first_dense = 1;
    c.dense_inter = 96;
    c.full_attn = vec![4, 8, 12, 13];

    let x = arr(&r, "in");
    let eo = arr(&r, "out");
    let bri = arr(&r, "block_residual_in");

    let in_norm = arr(&r, "input_layernorm_weight");
    let post_norm = arr(&r, "post_attention_layernorm_weight");
    let attn_res_norm = arr(&r, "self_attention_res_norm_weight");
    let attn_res_proj = arr(&r, "self_attention_res_proj_weight");
    let mlp_res_norm = arr(&r, "mlp_res_norm_weight");
    let mlp_res_proj = arr(&r, "mlp_res_proj_weight");

    // All weight storage is owned by this frame and the views borrow from it, exactly as
    // the C test holds the packed `float *` on its stack.
    let moe_w = LayerMoeWeights::load(&r, &c);
    let attn_w = LayerAttnWeights::load(&r, is_mla);
    let moe = moe_w.view();
    let attn = attn_w.view(is_mla);

    let lw = LayerW {
        in_norm: &in_norm,
        post_norm: &post_norm,
        attn_res_norm: &attn_res_norm,
        attn_res_proj: &attn_res_proj,
        mlp_res_norm: &mlp_res_norm,
        mlp_res_proj: &mlp_res_proj,
        attn,
        moe: Some(moe),
        dense_gate: None,
        dense_up: None,
        dense_down: None,
    };

    let din = shape(&r, "in");
    let t = din[1] as usize;
    let dbr = shape(&r, "block_residual_in");
    let nb_in = dbr[1] as usize;
    let maxb = (c.n_layers / c.attn_res_block + 2) as usize;
    let e = c.hidden as usize;

    let mut h = vec![0.0f32; t * e];
    let mut br = vec![0.0f32; t * maxb * e];
    let mut sc = vec![0.0f32; k3::ops::layer_scratch(&c, t)];
    let p = (c.kda_heads * c.kda_head_dim) as usize;
    let mut st = vec![0.0f32; p * c.kda_head_dim as usize + 3 * p * (c.conv_k - 1) as usize];
    let mut nb = nb_in;

    h.copy_from_slice(&x);
    for ti in 0..t {
        for b in 0..nb_in {
            br[(ti * maxb + b) * e..(ti * maxb + b + 1) * e]
                .copy_from_slice(&bri[(ti * nb_in + b) * e..(ti * nb_in + b + 1) * e]);
        }
    }
    decoder_layer(
        &mut h,
        &mut br,
        &mut nb,
        &lw,
        &c,
        li,
        t,
        Some(&mut st),
        &mut sc,
        None,
    );
    assert_close(file, &h, &eo, f.atol, f.rtol);
}

#[test]
fn layer_kda() {
    layer_case("layer_kda");
}

#[test]
fn layer_mla() {
    layer_case("layer_mla");
}

// ---------------------------------------------------------------------- mxfp4 ----

#[test]
fn mxfp4_case() {
    // t_mxfp4. test_ops.c:743. Dequant, checked against REAL Kimi K3 checkpoint bytes.
    // Exact equality: dequant is a table lookup times a power of two, so there is no
    // rounding anywhere and anything but a bit-exact match is a bug. The negative case
    // (asserting the swapped-nibble result is NOT produced) is the nibble-order guard.
    let f = Fixtures::ops();
    let r = match f.load_mxfp4() {
        Some(v) => v,
        None => {
            // A skip is a failure, exactly as the C harness counts it. test_ops.c:752-755.
            panic!("mxfp4: fixture absent (run tools/fetch_mxfp4.py); a skip is not a pass");
        }
    };
    let rows = num_i32(&r, "rows", 0) as usize;
    let pcols = num_i32(&r, "packed_cols", 0) as usize;
    let grp = num_i32(&r, "group_size", 32) as usize;
    let ef = arr(&r, "expected");
    assert!(rows > 0 && pcols > 0, "mxfp4: rows/packed_cols missing");
    let p = arr_u8(&r, "packed");
    let s = arr_u8(&r, "scales");
    let width = pcols * 2;
    let mut y = vec![0.0f32; rows * width];
    mxfp4_dequant(&mut y, &p, &s, rows, pcols, grp);
    assert_eq!(y.len(), ef.len(), "mxfp4: output length mismatch");
    let mut bad = 0usize;
    let mut worst = 0.0f64;
    let mut at = 0usize;
    for i in 0..y.len() {
        let d = ((y[i] as f64) - (ef[i] as f64)).abs();
        if d > worst {
            worst = d;
            at = i;
        }
        if d != 0.0 {
            bad += 1;
        }
    }
    assert_eq!(
        bad,
        0,
        "mxfp4: {bad} of {} elements differ, worst {worst:.7} at {at} (got {:.7} want {:.7})",
        y.len(),
        y[at],
        ef[at]
    );

    // NIBBLE ORDER IS A CONVENTION, NOT A RULE: the low nibble of each byte is the EVEN
    // element. Reversing it yields a matrix with exactly the right values in the wrong
    // places, so every statistic looks perfect and the model is wrong. Assert the
    // swapped-nibble result is NOT produced: dequant with the nibbles swapped must
    // disagree with the expected output somewhere. This is the guard the C test's
    // comment block describes; the explicit check lives here because it is the only
    // place that has the real bytes. k3_ops.c:1331, dispatch.rs mxfp4_dequant.
    let mut y_swap = vec![0.0f32; rows * width];
    mxfp4_dequant_swap(&mut y_swap, &p, &s, rows, pcols, grp);
    let mut swap_disagrees = false;
    for i in 0..y_swap.len() {
        if y_swap[i] as f64 != ef[i] as f64 {
            swap_disagrees = true;
            break;
        }
    }
    assert!(
        swap_disagrees,
        "mxfp4: swapped-nibble dequant matched the expected output, which means the \
         nibble order is NOT actually being enforced (low nibble must be the EVEN element)"
    );
}

/// A dequant that swaps the nibble convention (high nibble first), used only to prove the
/// real `mxfp4_dequant` does NOT produce this result. Mirrors `mxfp4_dequant` line for line
/// except for the nibble extraction.
fn mxfp4_dequant_swap(
    out: &mut [f32],
    packed: &[u8],
    scales: &[u8],
    rows: usize,
    pcols: usize,
    group: usize,
) {
    let width = pcols * 2;
    let ngrp = width.div_ceil(group);
    let e2m1 = k3::ops::dispatch::E2M1;
    let e8m0 = k3::ops::dispatch::E8M0;
    for r in 0..rows {
        let pr = &packed[r * pcols..(r + 1) * pcols];
        let sr = &scales[r * ngrp..(r + 1) * ngrp];
        let orow = &mut out[r * width..(r + 1) * width];
        for g in 0..ngrp {
            let mult = e8m0[sr[g] as usize];
            let lo = g * group;
            let hi = core::cmp::min(lo + group, width);
            for i in lo..hi {
                let byte = pr[i >> 1];
                // SWAPPED: high nibble is the EVEN element here.
                let nib = if i & 1 != 0 { byte & 0x0F } else { byte >> 4 };
                orow[i] = e2m1[nib as usize] * mult;
            }
        }
    }
}

// ------------------------------------------------------------------ matmul_bf16 ----

#[test]
fn matmul_bf16_case() {
    // t_matmul_bf16. test_ops.c:811. k3_matmul_bf16 must equal k3_matmul EXACTLY, not
    // approximately. Both widen the same bf16 values to the same f32 values (a left shift
    // by 16, which is lossless), then accumulate in double in the same order with the same
    // sixteen partial sums. So the only way they can differ is if one of them is wrong.
    //
    // This test needs no fixture. It generates bf16 bit patterns directly, which also means
    // it covers values a Gaussian sample would never produce - the checkpoint contains
    // denormals and very large exponents, and the widen must handle them by construction
    // rather than by luck.
    let inp = 257usize; // deliberately not a multiple of 4
    let out = 129usize;
    let mut wb = vec![0u16; inp * out];
    let mut wf = vec![0.0f32; inp * out];
    let mut x = vec![0.0f32; inp];
    let mut ya = vec![0.0f32; out];
    let mut yb = vec![0.0f32; out];

    let mut s: u32 = 0xC0FFEE;
    for i in 0..inp * out {
        s ^= s << 13;
        s ^= s >> 17;
        s ^= s << 5;
        // Any 16-bit pattern EXCEPT the NaN/Inf exponent, which would make every
        // comparison trivially NaN and prove nothing.
        let mut h = (s >> 8) as u16;
        if ((h >> 7) & 0xFF) == 0xFF {
            h &= 0x7F7F;
        }
        wb[i] = h;
        wf[i] = bf16f(h); // the SAME value, stored wide
    }
    for i in 0..inp {
        s ^= s << 13;
        s ^= s >> 17;
        s ^= s << 5;
        x[i] = (s >> 8) as f32 / 8388608.0 - 1.0;
    }

    matmul(&mut ya, &x, &wf, inp);
    matmul_bf16(&mut yb, &x, &wb, inp);

    let mut bad = 0usize;
    for o in 0..out {
        if ya[o].to_bits() != yb[o].to_bits() {
            bad += 1;
        }
    }
    assert_eq!(
        bad, 0,
        "matmul_bf16: {bad}/{out} rows differ from the fp32 path"
    );
}

// ----------------------------------------------------------- dispatched vs plain ----

/// A deterministic xorshift32, matching the C test's `s ^= s << 13; s ^= s >> 17; s << 5`
/// generator. No `rand`: the test must produce the same sequence on every run and every
/// platform, and the C gate does the same.
fn lcg_next(s: &mut u32) -> u32 {
    *s ^= *s << 13;
    *s ^= *s >> 17;
    *s ^= *s << 5;
    *s
}

/// The 16-lane f64 partition and reduction tree from `dispatch::dot_f32`, reproduced here
/// in the test so the dispatched kernel can be checked against it bit for bit. This is the
/// Rust replacement for the C build's scalar-vs-AVX2 gate: `dispatch.rs` exposes
/// `pub(crate) fn plain()` and `pub(crate) fn kernels()`, which an integration test cannot
/// reach, so the only way an external test can assert the selected kernels agree with the
/// un-multiversioned bodies is to rebuild the same reduction here and compare `to_bits`.
fn ref_dot_f32(row: &[f32], x: &[f32]) -> f64 {
    let n = row.len();
    let mut a = [0.0f64; 16];
    let mut i = 0usize;
    while i + 15 < n {
        for l in 0..16 {
            a[l] = (row[i + l] as f64).mul_add(x[i + l] as f64, a[l]);
        }
        i += 16;
    }
    let b0 = (a[0] + a[4]) + (a[8] + a[12]);
    let b1 = (a[1] + a[5]) + (a[9] + a[13]);
    let b2 = (a[2] + a[6]) + (a[10] + a[14]);
    let b3 = (a[3] + a[7]) + (a[11] + a[15]);
    let mut acc = (b0 + b1) + (b2 + b3);
    while i < n {
        acc = (row[i] as f64).mul_add(x[i] as f64, acc);
        i += 1;
    }
    acc
}

/// The 16-lane f64 partition and reduction tree from `dispatch::dot_bf16`, reproduced here
/// for the same reason. bf16 -> f32 is a pure 16-bit left shift.
fn ref_dot_bf16(row: &[u16], x: &[f32]) -> f64 {
    let n = row.len();
    let mut a = [0.0f64; 16];
    let mut i = 0usize;
    while i + 15 < n {
        for l in 0..16 {
            a[l] = (bf16f(row[i + l]) as f64).mul_add(x[i + l] as f64, a[l]);
        }
        i += 16;
    }
    let b0 = (a[0] + a[4]) + (a[8] + a[12]);
    let b1 = (a[1] + a[5]) + (a[9] + a[13]);
    let b2 = (a[2] + a[6]) + (a[10] + a[14]);
    let b3 = (a[3] + a[7]) + (a[11] + a[15]);
    let mut acc = (b0 + b1) + (b2 + b3);
    while i < n {
        acc = (bf16f(row[i]) as f64).mul_add(x[i] as f64, acc);
        i += 1;
    }
    acc
}

/// The 8-lane f64 partition and per-group reduction tree from `dispatch::dot_mxfp4`,
/// reproduced here. Each group of 32 is expanded to `wf[64]` via the E2M1 pair table, dotted
/// with eight f64 lanes, reduced `(s0+s4)+(s1+s5)...`, and the group's E8M0 scale is applied
/// as a separate multiply-then-add.
fn ref_dot_mxfp4(packed: &[u8], scales: &[u8], x: &[f32], input: usize, group: usize) -> f64 {
    let ngrp = input.div_ceil(group);
    let gbyte = group / 2;
    let mut acc = 0.0f64;
    for g in 0..ngrp {
        let sb = scales[g];
        if sb == 255 {
            continue;
        }
        let pb = &packed[g * gbyte..];
        let xg = &x[g * group..];
        let n = core::cmp::min(input - g * group, group);
        let mut wf = [0.0f32; 64];
        let half = n >> 1;
        for j in 0..half {
            let pv = &k3::ops::dispatch::E2M1_PAIR[pb[j] as usize];
            wf[2 * j] = pv[0];
            wf[2 * j + 1] = pv[1];
        }
        if n & 1 != 0 {
            wf[n - 1] = k3::ops::dispatch::E2M1_PAIR[pb[half] as usize][0];
        }
        let mut s = [0.0f64; 8];
        let mut i = 0usize;
        while i + 7 < n {
            for l in 0..8 {
                s[l] = (wf[i + l] as f64).mul_add(xg[i + l] as f64, s[l]);
            }
            i += 8;
        }
        let b0 = s[0] + s[4];
        let b1 = s[1] + s[5];
        let b2 = s[2] + s[6];
        let b3 = s[3] + s[7];
        let mut sub = (b0 + b1) + (b2 + b3);
        while i < n {
            sub = (wf[i] as f64).mul_add(xg[i] as f64, sub);
            i += 1;
        }
        acc += sub * k3::ops::dispatch::E8M0[sb as usize] as f64;
    }
    acc
}

/// Build a deterministic f32 in [-1, 1) from the LCG, matching the C scale_test.c fill()
/// shape (which uses the same xorshift and the same `/ 8388608.0 - 1.0` mapping).
fn lcg_f32(s: &mut u32) -> f32 {
    (lcg_next(s) >> 8) as f32 / 8388608.0 - 1.0
}

#[test]
fn dispatched_matches_plain_reference() {
    // This is the Rust replacement for the C build's scalar-vs-AVX2 gate.
    //
    // `dispatch.rs` multiversions the row kernels on x86-64: it stamps each body out once
    // plain and once under `#[target_feature(enable = "avx2,fma")]`, then selects between
    // them at startup via a `OnceLock` of function pointers. An integration test cannot
    // reach the `pub(crate) fn plain()` / `pub(crate) fn kernels()` selectors, so the only
    // way to assert the selected kernels agree with the un-multiversioned bodies is to
    // rebuild the same lane partitions and reduction trees here and compare `f32::to_bits`
    // on deterministic pseudo-random data. If the dispatched path ever diverged from this
    // reference, it would mean the AVX2 clone introduced a reassociation or a different
    // widen - which is the exact bug the C gate exists to catch.
    //
    // On aarch64 FMA and NEON are baseline, so the plain body already compiles to `fmla`
    // and there is nothing to select; the test still passes because the reference is the
    // same arithmetic the plain body uses.
    let mut s: u32 = 0xDEADBEEF;

    // ---- matmul (f32) ----
    let inp = 257usize;
    let out = 66usize; // exercises the `> 64` parallel path
    let mut w = vec![0.0f32; out * inp];
    let mut x = vec![0.0f32; inp];
    for v in &mut w {
        *v = lcg_f32(&mut s);
    }
    for v in &mut x {
        *v = lcg_f32(&mut s);
    }
    let mut y = vec![0.0f32; out];
    matmul(&mut y, &x, &w, inp);
    let mut bad = 0usize;
    for o in 0..out {
        let want = ref_dot_f32(&w[o * inp..o * inp + inp], &x) as f32;
        if y[o].to_bits() != want.to_bits() {
            bad += 1;
        }
    }
    assert_eq!(
        bad, 0,
        "matmul: {bad}/{out} rows differ from the reference dot"
    );

    // ---- matmul_bf16 ----
    let mut wb = vec![0u16; out * inp];
    let mut wf = vec![0.0f32; out * inp];
    for i in 0..out * inp {
        let mut h = (lcg_next(&mut s) >> 8) as u16;
        if ((h >> 7) & 0xFF) == 0xFF {
            h &= 0x7F7F;
        }
        wb[i] = h;
        wf[i] = bf16f(h);
    }
    let mut x2 = vec![0.0f32; inp];
    for v in &mut x2 {
        *v = lcg_f32(&mut s);
    }
    let mut yb = vec![0.0f32; out];
    let mut yf = vec![0.0f32; out];
    matmul_bf16(&mut yb, &x2, &wb, inp);
    matmul(&mut yf, &x2, &wf, inp);
    let mut bad = 0usize;
    for o in 0..out {
        // bf16 path must be bit-identical to the f32 path (same widen, same tree) AND to
        // the reference dot.
        if yb[o].to_bits() != yf[o].to_bits() {
            bad += 1;
        }
        let want = ref_dot_bf16(&wb[o * inp..o * inp + inp], &x2) as f32;
        if yb[o].to_bits() != want.to_bits() {
            bad += 1;
        }
    }
    assert_eq!(
        bad, 0,
        "matmul_bf16: {bad}/{out} rows differ from the f32 path or reference"
    );

    // ---- matmul_mxfp4 ----
    // A small but non-trivial MXFP4 matrix: input=64 (one full group of 32 plus a partial
    // group), rows=70 (> 64, parallel path). Packed cols = input/2 = 32 bytes/row. One
    // E8M0 scale per 32 elements = 2 scales/row. The group size is the model's 32.
    let inp_m = 64usize;
    let rows_m = 70usize;
    let group = 32usize;
    let pcols = inp_m / 2;
    let ngrp = inp_m.div_ceil(group);
    let mut packed = vec![0u8; rows_m * pcols];
    let mut scales = vec![0u8; rows_m * ngrp];
    for v in &mut packed {
        *v = (lcg_next(&mut s) >> 8) as u8;
    }
    for v in &mut scales {
        // Avoid 255 (NaN) and 0 (tiny) so every group contributes a normal scale.
        *v = ((lcg_next(&mut s) >> 8) % 254 + 1) as u8;
    }
    let mut xm = vec![0.0f32; inp_m];
    for v in &mut xm {
        *v = lcg_f32(&mut s);
    }
    let mut ym = vec![0.0f32; rows_m];
    matmul_mxfp4(&mut ym, &xm, &packed, &scales, inp_m, group);
    let mut bad = 0usize;
    for r in 0..rows_m {
        let want = ref_dot_mxfp4(
            &packed[r * pcols..(r + 1) * pcols],
            &scales[r * ngrp..(r + 1) * ngrp],
            &xm,
            inp_m,
            group,
        ) as f32;
        if ym[r].to_bits() != want.to_bits() {
            bad += 1;
        }
    }
    assert_eq!(
        bad, 0,
        "matmul_mxfp4: {bad}/{rows_m} rows differ from the reference dot"
    );
}

// ----------------------------------------------------------------- sanity l2norm ----

#[test]
fn l2norm_case() {
    // A quick sanity that l2norm matches the reference's sum-of-squares with eps inside the
    // rsqrt (NOT the mean). This is invariant 1's neighbour: using the mean here scales
    // every q and k by sqrt(d_k) and quietly changes the attention temperature. The
    // kernel is exercised inside kda_layer above, but the standalone check pins the
    // formula directly. k3_ops.c:792.
    let mut v = [3.0f32, 4.0, 0.0, 0.0];
    l2norm(&mut v, 1e-6);
    // sum of squares = 25, so inv = 1/sqrt(25 + eps) and each element is scaled by ~0.2.
    // Dividing by sqrt(5) instead would be the mean-based form this kernel deliberately
    // is not.
    let inv = 1.0 / (25.0f32 + 1e-6).sqrt();
    let expect0 = 3.0 * inv;
    let expect1 = 4.0 * inv;
    assert!(
        (v[0] - expect0).abs() < 1e-5 && (v[1] - expect1).abs() < 1e-5,
        "l2norm: got [{}, {}, {}, {}] expected [{}, {}, 0, 0]",
        v[0],
        v[1],
        v[2],
        v[3],
        expect0,
        expect1
    );
    assert_eq!(v[2], 0.0);
    assert_eq!(v[3], 0.0);
}
